import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TrainerService {

  constructor() { }

  //This will be generated by the Server
  getTrainersData(){
    
    return [
      {name: 'Farcas Rares', description: 'Antrenor personal, Manager fitness de grup', image_src: 'rares.jpg'},
      {name: 'Imre Andreea', description: 'Profesor de yoga, Antrenor personal, Fitness de grup', image_src: 'andreea.jpg'},
      {name: 'Gabos Monica', description: 'Instructor cycling, Antrenor personal', image_src: 'monica.jpg'},
      {name: 'Balint Zoltan', description: 'Antrenor personal, Fitness de grup, Instructor Aerobic', image_src: 'zoltan.jpg'}
    ];
  }
}
